### ISSUE TITLE
не изменяются путь на JS/CSS в dist/*.html

### ISSUE THREAD

**Issue by ilyar** [awinogradov/generator-bem-ng#32]
после выполнения сборки, путь на стили и скрипты остается прежним:

``` html
...
  <!--[if gt IE 9]><!-->
  <link rel="stylesheet" href="_index.css"/>
  <!--<![endif]--><!--[if gte IE 6]>
  <link rel="stylesheet" href="_index.ie.css"/><![endif]-->
...
<script src="_index.js"></script>
...
```

**Comment by awinogradov** [comment]
Это не совсем ошибка. Этот бандл копируется напрямую из [project-stub](https://github.com/bem/project-stub/blob/bem-core/desktop.bundles/index/index.bemjson.js). В будущем он будет заменен на более расширенный и демонстрирующий возможности БЭМ из библиотеки [bem-example](https://github.com/verybigman/bem-example). Пути поправлю в версии 0.0.7, ориентировочно 5-6 марта.

**Comment by ilyar** [comment]
Понятно, спасибо за пояснение.

**Comment by ilyar** [comment]
:+1: awesome!

**Comment by ilyar** [comment]
хм, оказывается путь надо было руками добавить в `index.bemjson.js`, но что в результате в окружении `development` получаем `styles.min.css`:

``` css
@import url(..\..\blocks\test\test.css);
```

не проверял в linux, но в windows стиль не импортируется, если `index.html` открыть в браузере (`file:///C:/path/dist/index.html` или `http://localhost:63342/project/dist/index.html`).

Еще не очевидно как запустить в `production`, установка в `make.js` или в перемененную окружения не виляет на сборку.

**Comment by awinogradov** [comment]
@ilyar не понял в чем проблема. Можешь подробнее описать? При смене окружения в make.js на production borschik должен сжимать файлы

**Comment by ilyar** [comment]
борщ делает то что должен делать )) и делает это в `bundles/index/_index.css` , а вот грант копирует в дистриб  `bundles/index/index.css`

**Comment by ilyar** [comment]
т.е. не `bundles/index/index.css`, а `bundles/merged/merged.css`

**Comment by awinogradov** [comment]
@ilyar я поправил. Больше проблем с этим возникнуть не должно. Что касается переменных окружения, то ты не видишь изменений из-за кэша в .bem/cache. Почисти его или пропиши в таске bem force:true.

**Comment by awinogradov** [comment]
@ilyar я добавил новый таск в Gruntfile bem:clean. Ты можешь его использовать для чистки кеша. Также теперь переменная окружения в make.js берется из project.json

**Comment by ilyar** [comment]
@verybigman мы увлеклись переменными окружения, предлагаю обсудить их отдельно в #36. Думаю что очистка кеша не изменит того что в окружении `development` в файле `styles.min.css` будут импорт `@import url(..\..\blocks\test\test.css);`

**Comment by awinogradov** [comment]
@ilyar читай коментарии выше
