### ISSUE TITLE
проблемка с созданием нового блока

### ISSUE THREAD

**Issue by ilyar** [awinogradov/generator-bem-ng#34]
``` bash
$ sudo npm i verybigman/generator-bem -g
$ mkdir project && cd $_
$ yo bem && yo bem:init
$ bem make
$ bem create -l blocks -b test
Error: Tech module with path '/home/ilyar/project/libs/bem-core/.bem/techs/browser.js.js' not found on require search paths

$ node -v && npm -v && yo -v && bem -v
v0.10.26
1.4.3
1.1.2
0.7.8
```

проблема в файле `.bem/levels/blocks.js`:

``` javascript
var PATH = require('path'),
    environ = require('bem-environ'),
    join = PATH.join,
```

решается в сгенерированном проекте так:

``` diff
var PATH = require('path'),
-    environ = require('bem-environ'),
+    environ = require('bem-environ')({ libDir: 'Значение из project.json:libDir' })
    join = PATH.join,
```

В проекте есть шаблон только для `init/templates/_bundles.js`,  вероятно `..bem/levels/blocks.js` берется как есть из **project-stub**, поэтому не понятно что пулреквестить.

**Comment by awinogradov** [comment]
@ilyar Да все верно, проблема присутствует. Как-то я упустил. Раньше был теплэйт для blocks.js. Надо его создать.

Кстати, уже не нужно писать:

``` bash
yo bem && yo bem:init
```

Достаточно просто:

``` bash
yo bem
```

И еще я не советую устанавливать пакеты от sudo.

**Comment by ilyar** [comment]
:+1:  проверил, работает!
