### ISSUE TITLE
Вопрос о base

### ISSUE THREAD

**Issue by ilyar** [awinogradov/generator-bem-ng#39]
Release 1.0.0 :joy_cat:  cool!

Я не понял назначение base и именно в ней описывается уровень `*.blocks/base/.bem` из этого следует что блоки создаются в ней `bem create -l desktop.blocks/base -b myblock`, какой work flow ты предполагаешь?

**Comment by awinogradov** [comment]
Все верно. Посмотри [сюда](https://github.com/verybigman/bem-protein/tree/master/blocks)

**Comment by awinogradov** [comment]
Я сегодня или завтра перепишу bem-protein под новую структура с платформами и разделением дизайна. Тогда все встанет на свои места.

**Comment by ilyar** [comment]
Получается это группировка блоков, отличная мысль. Но по моему такая настройка должна быть рекомендацией, а не основной структурой, тем более уровень для группировки блоков можно создать командой:

```
bem create level -l desktop.blocks -o desktop.blocks base 
```

**Comment by awinogradov** [comment]
Это удобно для организации библиотеки. В проекте, возможно так и не стоит поступать. Я попозже поправлю это, я просто тестирую работоспособность этой структуры для bem-protein и внутренних библиотек.
