### ISSUE TITLE
Error when executing gulp command

### ISSUE THREAD

**Issue by dima716** [awinogradov/generator-bem-ng#59]
Hi, @awinogradov !

I's trying to run `gulp` after running `yo bem-ng` but get an error instead.

![0477347198](https://cloud.githubusercontent.com/assets/8137279/10574902/9757d73e-7661-11e5-85ba-f9520e79470b.jpg)

Any help would be greatly appreciated.

**Comment by dima716** [comment]
The problem was in old version of browsersync. Changed version to `~2.7.1` and now it works

**Comment by awinogradov** [comment]
Its cool!;)
